### ISSUE TITLE
Convert Currency doesn't work after latest commit

### ISSUE THREAD

**Issue by ashkanr** [hlissner/lb6-actions#24]
https://www.dropbox.com/s/xi17y2n1jqc4z84/Screenshot%202016-02-17%2014.00.59.jpg?dl=0

**Comment by hlissner** [comment]
Sorry about that! It's fixed now.

**Comment by Maetthu24** [comment]
I downloaded Convert Currency today, and for me it still doesn't work, I get the exact same error as @ashkanr. It seems that the shared scripts are still included even though they don't exist anymore?

**Comment by hlissner** [comment]
Just to be sure, you installed it from the [download link](https://v0.io/dl/launchbar/Convert%20Currency.lbaction.zip) on the [front page](https://github.com/hlissner/lb6-actions) right? 

If you downloaded/cloned the repo, you need to run `rake` before you install any of the actions.

**Comment by Maetthu24** [comment]
Thanks a lot, I had downloaded the whole repo because I wanted to try a lot of your actions. I downloaded it again using the download link, it's now working perfectly fine!
Thanks for the awesome work!

**Comment by hlissner** [comment]
No problem. There are download links for all the actions on the [front page](https://github.com/hlissner/lb6-actions) to save you the hassle. Let me know if any of the others give you trouble!
